# FAKE-08 -> Samsung Tizen TV web app.
#
#   source ~/emsdk/emsdk_env.sh
#   make -j$(nproc)      # -> app/fake08.js (engine, wasm inlined)
#   make wgt             # + sign with the active profile -> FAKE-08.wgt (your own TV)
#   make release TZ_PROFILE=<profile>   # no PC address, signed with <profile>
#                        #   -> release/FAKE-08.wgt (for a GitHub release)
#   make serve           # desktop test at http://localhost:8000
#   make serve-carts CARTS_DIR=<folder>   # share carts with the TV (tools/cart_server.py)
#
# The core is FAKE-08 with the TV patches, a git submodule at FAKE08_DIR (see
# TV-PATCHES.md there); src/web_host.cpp is this platform's Host.

CXX := em++
BUILD := build
OUT := app/fake08.js
FAKE08_DIR ?= third_party/fake-08
TZ ?= $(or $(shell command -v tz 2>/dev/null),$(HOME)/.tizen-extension-platform/server/sdktools/data/tools/tizen-core/tz)
RELEASE_WGT := release/FAKE-08.wgt

# The PC the TV downloads carts from. `make` and `make wgt` default it to this
# machine's LAN address, baked into app/settings.js; it can be changed on the
# TV. `make release` leaves it empty.
CART_PORT ?= 8808
PC_IP ?= $(shell ip route get 192.0.2.1 2>/dev/null | awk '{for (i = 1; i < NF; i++) if ($$i == "src") print $$(i + 1)}')
PC_URL ?= $(if $(PC_IP),http://$(PC_IP):$(CART_PORT))

ifeq ($(wildcard $(FAKE08_DIR)/source/vm.cpp),)
ifneq ($(filter-out clean serve-carts,$(or $(MAKECMDGOALS),all)),)
$(error FAKE-08 not found in $(FAKE08_DIR). Run `git submodule update --init --recursive`, or set FAKE08_DIR)
endif
endif

# Left out: main.cpp owns a desktop main(), hostCommonFunctions.cpp needs
# simpleini/miniz for settings and zip carts, ltests.c is Lua's test harness.
# Nothing else from FAKE-08 (platform/, test/, carts/) is used.
CORE_SRCS := $(filter-out $(FAKE08_DIR)/source/main.cpp $(FAKE08_DIR)/source/hostCommonFunctions.cpp,$(wildcard $(FAKE08_DIR)/source/*.cpp)) \
             $(FAKE08_DIR)/libs/lodepng/lodepng.cpp
LUA_SRCS := $(filter-out $(FAKE08_DIR)/libs/z8lua/ltests.c,$(wildcard $(FAKE08_DIR)/libs/z8lua/*.c))
OBJS := $(BUILD)/src/web_host.o \
        $(patsubst $(FAKE08_DIR)/%.cpp,$(BUILD)/fake08/%.o,$(CORE_SRCS)) \
        $(patsubst $(FAKE08_DIR)/%.c,$(BUILD)/fake08/%.o,$(LUA_SRCS))
# Objects of the core don't encode FAKE08_DIR in their path, so rebuild them
# all when it points somewhere else.
CORE_STAMP := $(BUILD)/fake08-dir.txt

# The fast paths of the TV patches (see TV-PATCHES.md in the fork); -fwrapv gives
# Lua's fixed point the wrap semantics it relies on. z8lua is C++ (fix32), so its
# .c files build as C++. The prefix map keeps FAKE08_DIR (possibly a path on
# this machine) out of the __FILE__ strings in the package.
CXXFLAGS := -O3 -std=gnu++17 -fwrapv -w -DLUA_USE_LONGJMP -ffile-prefix-map=$(FAKE08_DIR)/=fake-08/ \
            -DPICO8_TLINE_FAST=1 -DPICO8_VM_HOT_CALLS=1 -DPICO8_VM_MEMORY_SUPEROPS=1 \
            -DPICO8_VM_FIELD_CACHE=1 -DPICO8_VM_PROFILE=0 -DPICO8_PERF_LOG=0 \
            -I$(FAKE08_DIR)/source -I$(FAKE08_DIR)/libs/z8lua -I$(FAKE08_DIR)/libs/lodepng

# Single file: the TV loads one .js from the package and never fetches a
# separate .wasm/.data. No carts are built in; the launcher copies them into
# the in-memory file system at run time (app/sources.js).
LDFLAGS := -O3 -sSINGLE_FILE=1 -sENVIRONMENT=web -sALLOW_MEMORY_GROWTH=1 \
           -sINITIAL_MEMORY=64MB -sSTACK_SIZE=1MB -sFORCE_FILESYSTEM=1 \
           -sEXPORTED_FUNCTIONS=_main,_malloc,_free,_p8_run_cart,_p8_stop_cart \
           -sEXPORTED_RUNTIME_METHODS=FS,ccall,UTF8ToString,stringToUTF8,lengthBytesUTF8

.PHONY: all wgt release serve serve-carts clean FORCE

# Shipped in the package next to the code they cover.
LICENSES := app/LICENSE app/LICENSE-FAKE-08.md app/THIRD-PARTY-NOTICES.md

all: $(OUT) app/settings.js $(LICENSES)

app/LICENSE: LICENSE
	cp $< $@
app/THIRD-PARTY-NOTICES.md: THIRD-PARTY-NOTICES.md
	cp $< $@
app/LICENSE-FAKE-08.md: $(FAKE08_DIR)/LICENSE.MD
	cp $< $@

settings_js = printf '/* Generated by the Makefile. */\nwindow.FAKE08_CONFIG = { pcUrl: "%s" };\n' "$(1)"

# Rewritten only when the address changes, so it doesn't dirty the package.
app/settings.js: FORCE
	@$(call settings_js,$(PC_URL)) > $@.tmp
	@cmp -s $@.tmp $@ && rm $@.tmp || { mv $@.tmp $@; echo "PC address for the TV: $(or $(PC_URL),none)"; }

$(CORE_STAMP): FORCE
	@mkdir -p $(dir $@)
	@echo "$(abspath $(FAKE08_DIR))" > $@.tmp
	@cmp -s $@.tmp $@ && rm $@.tmp || { mv $@.tmp $@; echo "FAKE-08: $(abspath $(FAKE08_DIR))"; }

$(OUT): $(OBJS)
	@echo "LD $@"
	@$(CXX) $(LDFLAGS) $(OBJS) -o $@
	@ls -l $@

$(BUILD)/src/%.o: src/%.cpp Makefile $(CORE_STAMP)
	@mkdir -p $(dir $@)
	@echo "C++ $<"
	@$(CXX) $(CXXFLAGS) -c $< -o $@

$(BUILD)/fake08/%.o: $(FAKE08_DIR)/%.cpp Makefile $(CORE_STAMP)
	@mkdir -p $(dir $@)
	@echo "C++ $<"
	@$(CXX) $(CXXFLAGS) -c $< -o $@

$(BUILD)/fake08/libs/z8lua/%.o: $(FAKE08_DIR)/libs/z8lua/%.c Makefile $(CORE_STAMP)
	@mkdir -p $(dir $@)
	@echo "C++ $<"
	@$(CXX) $(CXXFLAGS) -x c++ -c $< -o $@

# `tz build` stages app/ into app/Debug/projects; `tz pack` signs it with the
# active security profile (see `tz security-profiles list`). For your own TV.
wgt: $(OUT) app/settings.js $(LICENSES)
	$(TZ) build -w app
	$(TZ) pack -w app
	cp app/Debug/app.wgt FAKE-08.wgt
	@ls -l FAKE-08.wgt

# release: for other people's TVs, from a staged copy of app/ with an empty PC
# address, signed with TZ_PROFILE (for example a profile with the generic Tizen
# SDK distributor certificate, see README.md). `tz` ignores -s and a
# signing_profile it can't use, and silently signs with the active profile, so
# the active profile is switched for the build and switched back afterwards,
# and the signers are printed.
RELEASE_STAGE := $(BUILD)/release/app
APP_FILES := config.xml tizen_web_project.yaml icon.png index.html main.js sources.js style.css

release: $(OUT) $(LICENSES)
	@test -n "$(TZ_PROFILE)" || { echo "make release: set TZ_PROFILE=<signing profile> (tz security-profiles list)"; exit 1; }
	@$(TZ) security-profiles list | grep -qxF '$(TZ_PROFILE)' || { echo "make release: no security profile named '$(TZ_PROFILE)'"; exit 1; }
	rm -rf $(BUILD)/release
	mkdir -p $(RELEASE_STAGE)
	cp $(addprefix app/,$(APP_FILES)) $(OUT) $(LICENSES) $(RELEASE_STAGE)/
	$(call settings_js,) > $(RELEASE_STAGE)/settings.js
	@prev=$$($(TZ) security-profiles list | sed -n 's/^Current Active Profile: //p'); \
	 trap '[ -n "$$prev" ] && $(TZ) security-profiles set-active "$$prev" >/dev/null && echo "Active profile back to $$prev"' EXIT; \
	 $(TZ) security-profiles set-active '$(TZ_PROFILE)' && \
	 $(TZ) build -w $(RELEASE_STAGE) && $(TZ) pack -w $(RELEASE_STAGE)
	@mkdir -p $(dir $(RELEASE_WGT))
	cp $(RELEASE_STAGE)/Debug/app.wgt $(RELEASE_WGT)
	@sh tools/wgt-signers.sh $(RELEASE_WGT)
	@ls -l $(RELEASE_WGT)

serve: $(OUT) app/settings.js $(LICENSES)
	cd app && python3 -m http.server 8000

serve-carts:
	@test -n "$(CARTS_DIR)" || { echo "make serve-carts: set CARTS_DIR=<folder with one subfolder per game>"; exit 1; }
	python3 tools/cart_server.py "$(CARTS_DIR)" --port $(CART_PORT)

FORCE:

clean:
	rm -rf $(BUILD) $(OUT) app/settings.js $(LICENSES) app/Debug FAKE-08.wgt release
